name: CI/CD for Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku Container Registry
        run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

      - name: Build Docker image
        run: docker build -t registry.heroku.com/auto-data-helper/web .

      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/auto-data-helper/web

      - name: Deploy app on Heroku
        run: |
          heroku container:release web -a auto-data-helper
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
