name: CI/CD Data Helper Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Container Registry (GCR)
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/data-helper-402621/data-helper:latest

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCR_JSON_KEY }}
          project_id: data-helper-402621

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials data-helper-cluster --region us-east1
          kubectl set image deployment/data-helper-deployment data-helper=gcr.io/data-helper-402621/data-helper:latest
